### ISSUE TITLE
Integracion en laravel 9

### ISSUE THREAD

**Issue by josuechevez** [flightsadmin/livewire-crud#3]
Este paquete funciona bien en laravel 9 lo unico que hay hacer es correr este comando y segui los pasos de la guia de la propia documentacion, esto permite ejecutarlo sin problemas pero cambia siempre los estilo, yo lo integre a la libreria adminLTE y me funciona bien.

```
composer require flightsadmin/livewire-crud:^*  -W 
```

![image](https://user-images.githubusercontent.com/67529112/206351165-ddeb3564-74b7-43ad-97e6-5c35fdc8c442.png)

**Comment by georgechitechi** [comment]
Version 2 was added including Vitejs asset bundler as required by Laravel ^9.19

This installing on Laravel <9.19 will use v1 which uses webpack 6.0
