### ISSUE TITLE
Routes?

### ISSUE THREAD

**Issue by alrik11es** [flightsadmin/livewire-crud#6]
I've been messing with this crud generator. I've struggled to get routes working.
How about suggest the user some route configs? Or just point to the way to use the CRUD results.

**Comment by georgechitechi** [comment]
When you run ```php artisan crud:install``` below Auth routes will be added to the routes file if you choose to Install Auth. If you dont install Auth, Below will not be added. This is from laravel/ui package

//Route Hooks - Do not delete//
Auth::routes();
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');


When you run ```php artisan crud:generate posts``` below Routes are added to the below ```//Route Hooks - Do not delete//```

Route::view('posts', 'livewire.posts.index')->middleware('auth');

![image](https://user-images.githubusercontent.com/52364198/216781722-d636a268-cee2-4146-ae65-de92f08f47d4.png)

Let me know if above helps.

**Comment by alrik11es** [comment]
Thanks for adding some examples. Strangely it didn't get populated when I ran the command. It seems there is some problem there.

**Comment by georgechitechi** [comment]
Can you run below command and advise if still issues; Just to test on a new Project, because I did and it worked as expected.
Please create and migrate posts migration file before running last command, or create any table of your choice in the database.
Run `composer create-project laravel/laravel:8 myapp` to create laravel 8 project.

```
composer create-project laravel/laravel myapp

composer require flightsadmin/livewire-crud

php artisan crud:install

php artisan crud:generate posts 
```

**Comment by alrik11es** [comment]
Oh! I forgot to run `php artisan crud:install`.

Thanks for the help.
